apiVersion: v1
kind: Pod
metadata:
  name: hello-app-pod
  labels:
    app: hello-app
spec:
  containers:
    - name: hello-app-container
      image: fbiville/hello-app
      env:
        - name: ENV_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name